path:
  wd: "/home/viki/Codes/MultiSource/3/multi_source_exp/MultiSourceExp/"
  data: "/home/viki/Codes/MultiSource/2/multi-source/data_set_2/"

setting:
  device: "cuda"
  batch_size: 100
  num_epochs: 20
  lr: 0.0001